fix: fail workflow if file upload fails

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -39,10 +39,15 @@ runs:
     - name: Upload results to AccuKnox
       run: |
         file=$(ls CHECKMARX-*.json | head -n1)
-        curl --location "https://${{ inputs.accuknox_endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=CX&save_to_s3=true&label_id=${{ inputs.label_id }}" \
+        RESPONSE=$(curl --location "https://${{ inputs.accuknox_endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=CX&save_to_s3=true&label_id=${{ inputs.label_id }}" \
           --header "Tenant-Id: ${{ inputs.tenant_id }}" \
           --header "Authorization: Bearer ${{ inputs.ak_token }}" \
-          --form "file=@$file"
+          --form "file=@$file")
+        echo "Response: $RESPONSE"
+        if [[ "$RESPONSE" != *"File received successfully"* ]]; then
+           echo "Error: Failed to push report to control plane"
+          exit 1
+        fi
       shell: bash
 
     - name: Upload Scan Results as Artifact
